version: '3.8'

services:
  auth:
    container_name: auth
    build: ./auth
    image: auth
    restart: always
    ports:
      - "3001:3001"
  tickets:
    container_name: tickets
    build: ./tickets
    image: tickets
    restart: always
    ports:
      - "3002:3002"
  orders:
    container_name: orders
    build: ./orders
    image: orders
    restart: always
    ports:
      - "3003:3003"
  payments:
    container_name: payments
    build: ./payments
    image: payments
    restart: always
    ports:
      - "3004:3004"
  expiration:
    container_name: expiration
    build: ./expiration
    image: expiration
    restart: always
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - 27017:27017
  client:
    container_name: client
    build: ./client
    image: client
    restart: always
    ports:
      - "3000:3000"