name: deploy-payments

on:
  push:
    branches:
      - master
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./payments
          push: true
          tags: pandyaronak007/payments:latest
      - name: Digital Ocean details
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save ticketing

      - name: Verify deployment
        run: kubectl rollout status deployment payments-depl
